// "What Markdown becomes", second half (see markdown-1.mjs).
export const ROWS_2 = [
	['12 Footnotes', 'Four footnotes: at the foot of the page in Word and the PDF, pop-up notes in the ebook. The one marked twice is one footnote; the one never marked is not in the book.', 'A footnote by number.[^1] One by name.[^a-name] One typed in place.^[This one is written where it is marked, with *italics* and [a link](https://example.com/note).] The first one again.[^1] And one whose text runs to a second paragraph.[^long]\n\n[^1]: The first footnote.\n[^a-name]: The footnote with a name.\n[^long]: The long footnote’s first paragraph.\n    Its second line, indented under it.\n[^never]: Nothing marks this one.\n'],
	['13 Comments', 'Both kinds of comment are left out: the book has only the words around them.', 'Before a comment %%this is an Obsidian comment%% and after it.\n\n%%\nA comment of several lines,\nall of it left out.\n%%\n\nBefore an HTML comment <!-- this is an HTML comment --> and after it.\n'],
	['14 Highlight', 'A highlight is its words, with no mark round them.', 'A sentence with ==three highlighted words== in the middle of it.\n'],
	['15 Tags', 'The line of tags is left out. The tag inside a sentence stays as typed, with a warning.', '#draft #needs-work #part/one\n\nA sentence with a #tag inside it, which stays.\n'],
	['16 Callouts', 'Each callout is a block quotation, its title in bold. One with no title of its own has its kind as the title or none; a folded one is exported whole.', '> [!note] A note with a title\n> The callout’s own words.\n\n> [!warning]\n> A warning with no title of its own.\n\n> [!tip]- Folded when it is read in Obsidian\n> Exported whole all the same.\n\n> [!quote] One callout\n> > [!info] inside another\n> > The inner callout’s words.\n'],
	['17 Quotations, lists and tables', 'The same in the book: a quotation, a quotation inside one, bullets, numbers, a list inside a list, a checklist, and a table with its columns aligned.', '> A quotation of two lines.\n> Its second line.\n>\n> > And a quotation inside it.\n\n- A bullet\n- Another\n    - One under it\n    - And a second\n- A third\n\n1. First\n2. Second\n    1. Second, first\n3. Third\n\n7. A list that starts at seven\n8. Eight\n\n- [ ] Not done\n- [x] Done\n\n| Left | Middle | Right |\n|:---|:---:|---:|\n| one | **two** | 3 |\n| a [[01 Properties\\|link]] | *four* | 5.50 |\n| and a pipe \\| in a cell | | 6 |\n'],
	['18 Code', 'Monospaced, as typed: nothing in it is curled or made a dash. Only a fenced block is a block of code.', 'A word of `inline code` in a sentence, with `"quotes" -- and ...` left alone.\n\n```js\nconst kept = "as typed"; // -- and ... too\nif (a < b && b > c) { return `${a}`; }\n```\n\n~~~\nA block fenced with tildes.\n    Its indent is kept.\n~~~\n'],
	['19 Math', 'As typed, with a warning. A price is not math.', 'Inline math $a_1^2 + b_2^2 = c^2$ in a sentence, and a price of $5 that is only a price.\n\n$$\n\\int_0^1 x^2 \\, dx = \\frac{1}{3}\n$$\n'],
	['20 Block ids', 'The id at the end of each paragraph is dropped: the sentence ends at its full stop.', 'A paragraph with a block id at its end. ^first-block\n\nAnother, linked to from elsewhere. ^b2\n\n- A list item with one ^item-id\n'],
	['Not in the table - HTML', 'Not a row of the table: what export does with HTML is not decided in the doc. Today its text stays and its tags go.', 'A <span class="x">spanned</span> word, a line<br>broken, <u>underlined words</u>, and <sup>raised</sup> text.\n\n<div align="center">A centred line.</div>\n'],
];
